apiVersion: v2
name: postgresql
description: A Helm chart for PostgreSQL
version: 0.1.0
appVersion: "16.3.0"
dependencies:
  - name: postgresql
    version: "15.5.4"
    repository: "https://charts.bitnami.com/bitnami"
