apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pychangecalc-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /calculator
        pathType: Prefix
        backend:
          service:
            name: pychangecalc-pychangecalc
            port:
              number: 80
